--- #YAML:1.0
name:                Net-NationalRail-LiveDepartureBoards
version:             0.01
abstract:            Live Departure Boards information
license:             perl
author:              
    - Tim Retout <diocles@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    SOAP::Lite:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
